# Created with YamlCreate.ps1 v2.2.13 $debug=NVS0.CRLF.7-4-1.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: OpenTofu.Tofu
PackageVersion: 1.6.0
InstallerLocale: en-US
InstallerType: zip
FileExtensions:
- tf
ReleaseDate: 2024-01-10
Installers:
- Architecture: x86
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: tofu.exe
    PortableCommandAlias: tofu
  InstallerUrl: https://github.com/opentofu/opentofu/releases/download/v1.6.0/tofu_1.6.0_windows_386.zip
  InstallerSha256: AAD5A2DE06A0AF4F5348F975E9326994123663283A7F6FF7A0615044FED44BD3
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: tofu.exe
    PortableCommandAlias: tofu
  InstallerUrl: https://github.com/opentofu/opentofu/releases/download/v1.6.0/tofu_1.6.0_windows_amd64.zip
  InstallerSha256: 9FCD60BDECD6B335392A4DDDD850DD1872A3BA1091F77079EEE3730FE43D3650
ManifestType: installer
ManifestVersion: 1.5.0
